### PR TITLE
Update unsafe.txt

### PR DESCRIPTION
**Pull request by klenndal**

### CODE REVIEW

**Review by taskylizard — APPROVED** [review]

**Comment by taskylizard** [comment]
Hello, thanks for the PR! Everything looks good to merge.

**Comment by ballszu** [comment]
the video streaming sites too? and seo spam

I mean its not wrong, but unnecessary for a gaming wiki

**Comment by taskylizard** [comment]
We do have a fair bit of content which are loosely related to gaming piracy, but other than that, this should be fine.

Also, I did mention in the FMHY to-do channel to PR if anyone wants to, since we had forked this from rust's gist but didn't progress much. It can come useful in the future if we give it some care.

**Pull request merged**
