### PR TITLE
Wiki translation into Romanian

### PR DESCRIPTION
**Pull request by Douper2**

### CODE REVIEW

**Review by taskylizard — COMMENTED** [review]
Are you going to translate the `description` fields?

**Comment by Douper2** [comment]
> > Are you going to translate the `description` fields?
> 
> I didn't think that it was necessary to translate that, but I will

Ok, I just changed thew description

**Comment by taskylizard** [comment]
I just noticed, you moved the files inside docs/ to the root of this project, I'll have to clean that up later.

Regarding `description`, yeah, it is needed for metadata tags as well as opengraph image generation, while you probably can skip doing this for now if you're busy.

I'll prepare the lunaria configuration files and related later today in your PR.

**Comment by Douper2** [comment]
> I just noticed, you moved the files inside docs/ to the root of this project, I'll have to clean that up later.
> 
> Regarding `description`, yeah, it is needed for metadata tags as well as opengraph image generation, while you probably can skip doing this for now if you're busy.
> 
> I'll prepare the lunaria configuration files and related later today in your PR.

Ok, also thanks for the notice about the description

**Comment by taskylizard** [comment]
You're now only left witb translating the sidebar.

**Comment by Douper2** [comment]
> You're now only left witb translating the sidebar.

Where is the sidebar text?

**Comment by taskylizard** [comment]
docs/.vitepress/locales/ro.ts

**Comment by taskylizard** [comment]
Nope, https://github.com/Douper2/wiki/blob/master/docs/.vitepress/locales/ro.ts, I committed the file myself for you.

**Comment by Douper2** [comment]
> Nope, https://github.com/Douper2/wiki/blob/master/docs/.vitepress/locales/ro.ts, I committed the file myself for you.

Most likely I forgot to upload the file containing the sidebar but now it's fixed

**Comment by taskylizard** [comment]
Thanks, I also now noticed that some pages still have their english fields (`title`, `description`), will you translate them?

**Comment by Douper2** [comment]
> Thanks, I also now noticed that some pages still have their english fields (`title`, `description`), will you translate them?

No problem, I just finished translating the description

**Review by taskylizard — APPROVED** [review]
Looks all good, thanks for the PR!

**Comment by Douper2** [comment]
I fixed another translation, could you merge it?

**Comment by taskylizard** [comment]
Make a new PR.

**Pull request merged**
