### PR TITLE
Begin rebrand

### PR DESCRIPTION
**Pull request by taskylizard**
- [ ] Add [i18n](https://vitepress.dev/guide/i18n)
- [x] Add our very own [theme](https://vitepress.dev/guide/extending-default-theme)
- [x] Use other niceties bundled with Vitepress https://vitepress.dev/reference/default-theme-badge
- [x] Deploy to [Github Pages](https://vitepress.dev/guide/deploy#github-pages) or Cloudflare Pages maybe

### CODE REVIEW

**Comment by Kazevic** [comment]
This is much more than I thought that would be done. Amazing work, dude.

I cannot really contribute much because I am more of a layman on that type of thing, but yeah, I know HTML and CSS, so maybe I can give some suggestions? I don't know, maybe HTML and CSS are too simple to have much that you could do to “optimize” it…

**Comment by taskylizard** [comment]
That is fine, it doesn't need much styling now.

**Comment by taskylizard** [comment]
Does the grammar here feel right? It doesn't really matter since it's on the home page but it's nice to show. https://github.com/r-piratedgames/megathread/blob/d2c58dcf0659bc3be4a4d14785cf45266da37c47/index.md?plain=1#L13-L22

**Comment by Kazevic** [comment]
Under the Favorite Picks' details, there should be a comma before “so”, and it should be “can rest assured”, without the “be”.

We can also see if those titles look better with sentence case or title case.

**Comment by taskylizard** [comment]
I fixed the grammar as you mentioned. Also replaced the Actively Updated and Translations emojis with more suitable ones.

> We can also see if those titles look better with sentence case or title case.
The titles look fine to me in any case.

**Comment by taskylizard** [comment]
As we are currently a single wiki page with no external files, it's slightly annoying to split the giant README.md into several chunks just so the page doesn't look like a big pile of shit.

The current solution i made was to split the sections by h2 headings (`##`) to `/docs/wiki` and create a `/docs/wiki/start.md` file with hyperlinks to all the other files, which works but i believe this is definitely jank. Need opinions.

**Comment by Kazevic** [comment]
I think it is better to split it, now that the other stuff is still not completely added. I am ok with doing it the easier way too, but it might end up slowing down further changes to the project.

**Comment by taskylizard** [comment]
Alright, I'll start work on that.

**Comment by taskylizard** [comment]
I wanted to give a update on this, as I was busy on another project (and an exciting one!).

- The single README.md was decoupled into multiple smaller ones, now I want to decide whether to keep the old layout or not (probably better not to?).
- The old translations have been archived, except yours (the russian one will be translated later), as well as decoupled like the main one.
- A contribution guide was added.

**Pull request merged**
